### ISSUE TITLE
libcrypt symlink for ssh

### ISSUE THREAD

**Issue by jargonzombies** [pypa/manylinux#1022]
Due to the manual removal of glibc's supplied `/lib64/libcrypt.so.1` in pursuit of #305, the use of `yum`-installed `ssh-agent` from the `openssh-clients` package for CI work no longer functions in the `manylinux2014` docker image. 

The error is the following: `ssh-agent: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory`. `ssh-agent` seems to be stubborn regarding the location of `libcrypt` and cannot be persuaded with `LD_LIBRARY_PATH`. I'm not sure what finally broke it since the changes regarding `libcrypt` are fairly old. 

I would suggest the addition of a `ln -s /usr/local/lib/libcrypt.so.1 /lib64/libcrypt.so.1` or similar. I'm quite okay with a `wontfix` due to other possible conflicts that I cannot foresee or refusal to support packages installed after docker start (understandable) as well since I can fix this in each run with minimal effort, but it might be nice for others, too.

**Comment by mayeut** [comment]
Thanks for the report.
The removal done at some point was not enough for `manylinux_2_24` and it's been done a bit more aggressively in 32dbdd17b93ceb553ae064ff8d4a802bd59448b4 which broke `manylinux2014`.
I didn't check why `LD_LIBRARY_PATH` is not honored with `ssh-agent` (`ldd $(which ssh-agent)` has no trouble finding the library but, as you reported, running `ssh-agent` fails). Before 32dbdd17b93ceb553ae064ff8d4a802bd59448b4, the symlink `/lib64/libcrypt.so.1` was recreated by the system at some point somehow... with the more aggressive removal, the system fails to recreate this symlink and that explains why it broke recently rather than at first attempts at removal a while ago.

A PR is on its way to fix this.

**Comment by jargonzombies** [comment]
Thank you @mayeut!
