### ISSUE TITLE
Platform for `manylinux_2_24`

### ISSUE THREAD

**Issue by wenleix** [pypa/manylinux#1274]
Hi, 

It looks like the LTS support for Debian 9 will end on June, 2022. I am wondering if it's still the recommended platform to build `manylinux_2_24`? 

Thanks!

**Comment by mayeut** [comment]
Unless you have specific needs requiring to build on `manylinux_2_24` rather than `manylinux2014`, I'd recommend building on `manylinux2014` even if the LTS support for Debian 9 wasn't this close. c.f. #1012
`manylinux1` & `manylinux2010` are both based on EOL OS and are still around for now, this will be the case for `manylinux_2_24`, at least until a newer image is available (no plans yet), c.f. #1249

**Comment by mayeut** [comment]
Closing as answered.
