### ISSUE TITLE
musl 1.2 image?

### ISSUE THREAD

**Issue by alex** [pypa/manylinux#1488]
As a result of https://blog.rust-lang.org/2023/05/09/Updating-musl-targets.html, I'd like to be able to produce images for a `musllinux_1_2` tag.

To do this, it'd be helpful to have a docker build env image. Thanks!

**Comment by TonyXiang8787** [comment]
I see there was a PR regarding `musllinux_1_2` in https://github.com/pypa/manylinux/pull/1225. But it was closed. The current GCC version of `musllinux_1_1` is only 9.3 and does not support most of C++20 features.  @henryiii, maybe we can revisit this issue due to the wish to have the modern compiler available in `musl` platform?

**Comment by bigcat88** [comment]
Also note, on musl_1_1 with GCC version 9.3.0, there is currently no way to create a default build of the latest google aom (AVIF) library.
Requires at least GCC 10 for arm64.

**Comment by mayeut** [comment]
musllinux_1_2 PR has been merged based on alpine:3.18 which is the latest released Alpine distro.
