### ISSUE TITLE
Did we just lose rsync from the manylinux image?

### ISSUE THREAD

**Issue by matthew-brett** [pypa/manylinux#160]
The h5py builds just started failing, with `rsync: command not found`:

https://travis-ci.org/MacPython/h5py-wheels/builds/345923582

That's true - the current docker image doesn't have `rsync`, but a previous image I have to hand does.  Did something change to remove it?

**Comment by jcfr** [comment]
@matthew-brett we maintain a set of images useful  to build software. Two of them encapsulate manylinux images and also add few useful tools like latest cmake, ninja, etc ... see https://github.com/dockcross/dockcross

**Comment by matthew-brett** [comment]
@jcfr - thanks for the pointer - I guess this isn't the right place to ask - but how strong is the guarantee that these will be maintained for the next - say - couple of years?

**Comment by jcfr** [comment]
Good question. 

If that helps answer, it turns out that @thewtex and I adopted the dockcross project since May 2015 and have been maintaining it so far and have a growing collection of available docker images. It will soon be three years ! And if that means anything, there is close to 600 stars and 17 different contributors from a broad set of organization.

**Comment by mayeut** [comment]
Closing stale issue.
In the future, added tools shall all get basic tests to prevent these kind of regression.
