### ISSUE TITLE
manylinux doesn't seem to support every use case

### ISSUE THREAD

**Issue by jawaff** [pypa/manylinux#243]
Hello, I'm currently interested in helping out an open sourced, Cython-based Python binding for [SFML](https://www.sfml-dev.org/index.php). My initial roadblock was that I couldn't publish a Debian based Binary Wheel to Pypi. (I think the error I was running into was a result of PEP513, because my Wheel didn't have the manylinux tag or anything else.)

I eventually came across manylinux and PEP513, but that didn't end up solving my issue entirely. Manylinux requires that only a minimal set of external libraries are used, but SFML requires OpenAL, Vorbis, Flac and some other media libraries probably. That seems to mean that pySFML isn't compatible with manylinux and therefore isn't able to publish to Pypi.

However, going through [PEP513](https://www.python.org/dev/peps/pep-0513/) I found the rejected alternatives section and it began with, "One alternative would be to provide separate platform tags for each Linux distribution (and each version thereof), e.g. RHEL6, ubuntu14_10, debian_jessie, etc." That alternative doesn't necessarily work well with the manylinux scenario, but it does help out my use case kind of.

Since SFML depends on libraries that are out of our control, the manylinux route seems impossible. So we essentially need to create a Wheel for each major Linux distro. The only thing that seems to be standing in our way of deploying to Pypi is the lack of a tagging system for specific Linux distros.

I may be going about this all wrong. If anybody can provide some help it would be greatly appreciated. I may just have to give up on Linux publications if I can't figure out a way to actually get the Wheels into Pypi.

**Comment by jawaff** [comment]
Here is the pySFML repo: https://github.com/Sonkun/python-sfml
I'm working on the automated build in my fork: https://github.com/jawaff/python-sfml

**Comment by njsmith** [comment]
There are lots of manylinux wheels on PyPI that depend on libraries like openal. They just do it by including a copy of the library inside the wheel, rather than relying on the system to provide it. (You'd need to do the same thing if making a wheel for Windows or macOS, since as far as I know they don't include openal with the operating system either.) The `auditwheel` tool that's used to prepare manylinux wheels not only checks that they'll work on multiple systems, but also takes care of patching up the wheel to include copies of any libraries like openal.

**Comment by rdb** [comment]
Depending on your licensing and depending on the library you can also build the libraries statically, so that they are included in your binaries.

Panda3D also has many dependencies including OpenAL and Vorbis, and we also publish manylinux wheels.  We do that by either building the library in question statically or by including it in the wheel.  The modules can have an rpath configured so that they look for dependency libraries in the same directory.

**Comment by jawaff** [comment]
Thank you two so much for the responses. What you guys are pitching makes sense. I'll try that out and see if I can get this working. I wasn't able to find any good manylinux examples. I might just go have a look at Panda3D's build scripts if they're available.
