### ISSUE TITLE
openssl missing from latest image

### ISSUE THREAD

**Issue by yhager** [pypa/manylinux#258]
Based on the build scripts, it should be in `/usr/local/ssl`, but I can't find it anywhere:

**Comment by njsmith** [comment]
No, this is intentional – you missed the part of the build scripts that removes it again :-).

We aren't able to be responsible for notifying and rebuilding packages after an openssl vulnerability is announced, so if you want to vendor openssl in your package then it's your responsibility to choose the version, keep it updated, etc.
