### ISSUE TITLE
The compiler used in x86_64 is different than the one used in i686

### ISSUE THREAD

**Issue by mattip** [pypa/manylinux#409]
PyPy started using the manylinux2010 docker images to build on x86. The compilers used in x86_64 and i686 are [different](https://github.com/pypa/manylinux/blob/master/docker/build_scripts/build.sh#L58), one is installed with `devtoolset-8` and the other with `devtoolset-7`. The devtoolset-8 compiler does not pass a test added in PyPy [2e8c4536e4](https://bitbucket.org/pypy/pypy/commits/2e8c4536e416b0c58ba0b1c3ca9e8eb702f46c48). The test can be described as testing  overflow behaviour when multiplying two ints with `-O3`: somehow **different** input to a complicated function yields the **same** output.

It seems to me that the two images should be using the same compiler, and I would prefer they both use devtoolset-7.

**Comment by njsmith** [comment]
The reason the 32 bit images are using the older compiler is that there's no longer any maintained version of gcc that works for manylinux and has support for 32 bit x86. So that image is stuck on the last available version.

If PyPy doesn't work correctly with newer gcc releases, then that seems like something the PyPy team needs to address directly, either by fixing PyPy or fixing gcc. Freezing the whole ecosystem on an obsolete compiler can't be the right solution.

**Comment by njsmith** [comment]
Well, maybe I phrased that a little too strongly. If there's a showstopper regression in the devtoolset-8 compiler, then that might be an argument for temporarily reverting to an earlier version until the bug is fixed. But from your post it's hard to tell whether there's actually a bug in gcc or not, or how hard it would be to work around. Is there an upstream gcc bug you can link to with more details?

**Comment by mattip** [comment]
It seems like an actual gcc bug, and I hope to report it soon to gcc. This is more of a "heads up, something may be off with the compiler used in manylinux2010, updates may be needed". There was already one update to the [devtools-8 package](https://cbs.centos.org/koji/buildinfo?buildID=26410) in August.

Maybe this should be marked as a documentation issue: a comment in the script as to why the diversion in the compiler versions would make it clear this was done on purpose.
