### ISSUE TITLE
Support Python 3.9

### ISSUE THREAD

**Issue by ijl** [pypa/manylinux#482]
rc1 was included for 3.8 (#313) not long before final. The current pre-release is 3.9.0a3. I would find it useful to have an alpha or beta personally but I don't know if that's ok generally.

**Comment by lkollar** [comment]
It probably makes sense to wait until the ABI is frozen so that wheels built using it will work on later releases. Not sure when that is planned with the 3.9 release schedule.

**Comment by dimaqq** [comment]
> It probably makes sense to wait until the ABI is frozen so that wheels built using it will work on later releases. Not sure when that is planned with the 3.9 release schedule.

What you are saying has the implication of:
* projects will invent their own way to build wheels, and/or
* python 3.9 cannot be properly tested

I doubt this chicken-and-egg is beneficial. Perhaps it makes sense to release or recommend building 3.9 packages with 3.8 ABI?

**Comment by lkollar** [comment]
@dimaqq We have been conservative about including pre-beta Python versions as it can easily happen that people start uploading wheels which will not work with subsequent versions of the interpreter. 

> What you are saying has the implication of:
> 
> * projects will invent their own way to build wheels, and/or
> * python 3.9 cannot be properly tested

All I'm saying is that we should wait for the first ABI stable version to make sure we don't produce bad wheels. There are still a few months until the final release, so hopefully this should give enough time to test and build wheels for 3.9.

> I doubt this chicken-and-egg is beneficial. Perhaps it makes sense to release or recommend building 3.9 packages with 3.8 ABI?

I don't understand this. Can you elaborate?

**Comment by dimaqq** [comment]
Sure, also caveat lector, I'm not an expert.
It goes like this:
* `pypa/manylinux` only includes 3.9 late in the python release schedule
* thus https://github.com/joerick/cibuildwheel/issues/370 doesn't include 3.9 in their thing
* thus https://github.com/scylladb/python-driver/issues/28 doesn't release 3.9 wheels because all builds are in CI
* thus I, end user, cannot test Python 3.9 using my server application that has the above as the dependency

I'm wondering what is the way to break the above cycle.

My current method relies on building locally from sdist's. Which helps test Python 3.9, but [not sure about this] possibly not the ABI?

Or am I perhaps just not getting something? 😕

**Comment by lkollar** [comment]
Given that 3.9b3 is now included in `manylinux`, all you need is to either wait until somebody adds it to the two other projects you depend on, or submit PRs yourself. The final release is scheduled for October, so there should be enough time left for testing.
