### ISSUE TITLE
Support travis_retry

### ISSUE THREAD

**Issue by letmaik** [pypa/manylinux#65]
It would be nice if the docker images contained a function similar to travis_retry. See https://github.com/jolicode/docker-images/issues/8 for an identical request in another docker image.

**Comment by njsmith** [comment]
Has this been a problem in some particular case?

I'm sure we'd accept a patch, though :-)

**Comment by neothemachine** [comment]
Well, network issues happen now and then. And it happened to me once already: https://travis-ci.org/neothemachine/rawpy/jobs/132149966
I ended up copying the travis_retry function in my build script: https://github.com/neothemachine/rawpy/blob/manylinux1/travis/build.sh#L5

**Comment by njsmith** [comment]
Oh, I see, hmm. I was thinking about uses inside our own docker build scripts. I think we should be careful about going down the road of adding lots of little handy scripts for users, because then we de facto end up maintaining this shell scripting library, with all the usual issues of maintaining a library (like worrying about accidentally breaking ABIs), and I don't think we have the resources to commit to that...

**Comment by neothemachine** [comment]
Sure, no worries. The workaround is too easy to bother really. Feel free to close this.
